### ISSUE TITLE
getJSON request failed! error

### ISSUE THREAD

**Issue by vladik-hbinov** [neilh10/thingspeakmultichannel-highcharts#2]
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://thingspeak.com/channels/8652/feed.json?callback=jQuery191010866738348939653_1603058258834&amp;offset=0&amp;results=2500;key=EAEX6922YVUKP3IP&_=1603058258835 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Does anyone has a fix for that?

**Comment by VastSky** [comment]
I second this request! 
So sad it stopped working. This HighCharts was a spectacular way to display ThingSpeak data!!!

https://community.thingspeak.com/forum/announcements/jsonp-requests-callback-parameter-are-deprecated/

**Comment by neilh10** [comment]
Yes I've seen it as well.  Thanks for the reference ~ I'm not an expert in this area and mostly just hosted this as a fork but will see where the code is. Since it has to have a key in it, it means its going to be custom code, or have to be passed into it.
I have recommended it for some projects, and one of them doesn't seem to have this problem
https://www.smartpedestriancounter.com/product

**Comment by VastSky** [comment]
Found the fix!
See post #27:
[https://forum.arduino.cc/index.php?topic=213058.msg4211691#msg4211691](https://forum.arduino.cc/index.php?topic=213058.msg4211691#msg4211691)

**Comment by makemeafirewall** [comment]
This issue seems to be resolved after merging my PR

**Comment by VastSky** [comment]
Here we go again! 
Same "getJSON request failed!" is back as of today. 
I wonder what Thingspeak changed to break this again?
